export enum FeatureComponent {
  BANNER = 'BANNER',
  OUR_RESULT = 'OUR_RESULT',
  SUCCESS_STORY = 'SUCCESS_STORY',
  OUR_INSTRUCTORS = 'OUR_INSTRUCTORS',
  WHY_HIRE = 'WHY_HIRE',
  HIRING_PARTNERS = 'HIRING_PARTNERS',
  TRAINEES_TECH = 'TRAINEES_TECH',
  TRAINEES_OVERVIEW = 'TRAINEES_OVERVIEW',
  HIRING_PARTNER_FEEDBACK = 'HIRING_PARTNER_FEEDBACK',
}
