export enum NotificationTypes {
 COURSE_ENROLLMENT = 'COURSE_ENROLLMENT',
 COURSE_COMPLETION = 'COURSE_COMPLETION',
 NEW_COURSE_AVAILABLE = 'NEW_COURSE_AVAILABLE',
 ASSIGNMENT_DUE = 'ASSIGNMENT_DUE',
 ASSIGNMENT_GRADED = 'ASSIGNMENT_GRADED',
 NEW_MESSAGE = 'NEW_MESSAGE',
 FORUM_REPLY = 'FORUM_REPLY',
 CERTIFICATE_AWARDED = 'CERTIFICATE_AWARDED',
 LIVE_SESSION_REMINDER = 'LIVE_SESSION_REMINDER',
 INVITE_TO_COURSE_BATCH = 'INVITE_TO_COURSE_BATCH'
}
